# Generated by Django 2.1.4 on 2019-07-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.TextField()),
                ('hotel_address', models.TextField()),
                ('mobile_number', models.IntegerField()),
                ('qty_required', models.IntegerField()),
                ('date_required', models.DateField()),
            ],
        ),
    ]
